'use strict';

// Load modules

const SchwiftyMigration = require('../lib');
const Path = require('path');
const Fs = require('fs');

// Test shortcuts

module.exports = ({ session, testUtils }) => {

    const { expect, lab: { describe, it }, utils } = testUtils;

    const clientName = session.options.knexConfig.client;
    const stepName = 'create';

    console.log(`Begin "${stepName}" tests for "${clientName}"`);

    describe(clientName + '_create', () => {

        it('adds models not in the db', (done) => {

            const actualFileName = 'create_1';
            const actualMigrationPath = Path.join(__dirname, 'migrations', clientName, 'actual', stepName);
            const expectedMigrationFilePath = Path.join(__dirname, 'migrations', 'expected', stepName, `${actualFileName}.js`);

            SchwiftyMigration.genMigrationFile({
                migrationGroups: [{
                    models: session.getModels_forStep(stepName, actualFileName),
                    migrationsDir: actualMigrationPath,
                    knex: session.knex
                }],
                mode: 'test'
            }, (err) => {

                expect(err).to.not.exist();

                const actualMigrationContents = utils.getLatestMigration(actualMigrationPath);
                const expectedMigrationContents = Fs.readFileSync(expectedMigrationFilePath).toString('utf8');

                // There's some pesky indentation that gets generated by schwifty-migration,
                // and my editor removes all trailing whitespace when I hit save

                // TODO make sure this is ok

                const actualMigrationContentsNoWhitespace = actualMigrationContents.replace(/ /g,'');
                const expectedMigrationContentsNoWhitespace = expectedMigrationContents.replace(/ /g,'');

                expect(actualMigrationContentsNoWhitespace).to.equal(expectedMigrationContentsNoWhitespace);

                done();
            });
        });
    });
};
