language: node_js

node_js:
  - "6"
  - "7"
  - "8"

services:
  - postgresql
  - mysql

env:
  - DB=postgres
  - DB=mysql

before_script:
  - psql -U postgres -c 'CREATE DATABASE schwifty_migration_test;'
  - mysql -e 'CREATE DATABASE schwifty_migration_test'
  # Wait for mysql service to respond
  - which mysql && until mysql -u root -e "show status" &>/dev/null; do sleep 1; done

after_script: "npm run coveralls"
