language: node_js

node_js:
  - "8"
  - "9"
  - "node"

services:
  - postgresql
  - mysql

env:
  - DB=postgres
  - DB=mysql

before_script:
  - psql -U postgres -c "CREATE DATABASE schwifty_migrate_diff_test;"
  - mysql -u root -e "CREATE DATABASE schwifty_migrate_diff_test"

after_script: "npm run coveralls"
