# Hints from https://gist.github.com/mceachen/2340726

mysql: &mysql
  adapter: mysql2
  username: root
  password:

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: schwifty_migration_test
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
